AWSTemplateFormatVersion: 2010-09-09
Description: An example CloudFormation template for Fargate.
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  LambdaLayerArn:
    Description: ARN of python dependancy layer
    Type: String
  ServiceLayerArn:
    Description: ARN of python dependancy layer
    Type: String


Resources:
  ReplicaAddrBucket: # Stores instance IP addresses
    Type: 'AWS::S3::Bucket'

  HeartbeatQueue:
    Type: AWS::SQS::Queue

  HealthWorker:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: health_worker.handle
      Runtime: python3.8
      CodeUri: ../gateway/health
      MemorySize: 256
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn
      Layers:
        - !Ref LambdaLayerArn
        - !Ref ServiceLayerArn
      Events:
        queue:
          Type: SQS
          Properties:
            Queue: !GetAtt HeartbeatQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          REPLICA_BUCKET: !Ref ReplicaAddrBucket

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html
        - PolicyName: !Sub '${AWS::StackName}-s3-crud'
          PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetLifecycleConfiguration
                  - s3:PutLifecycleConfiguration
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::${ReplicaAddrBucket}
                  - !Sub arn:${AWS::Partition}:s3:::${ReplicaAddrBucket}/*
                Effect: Allow
        - PolicyName: !Sub '${AWS::StackName}-sqs-send'
          PolicyDocument:
            Statement:
              - Action:
                  - sqs:SendMessage*
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - !GetAtt HeartbeatQueue.Arn
                Effect: Allow

Outputs:
  HeartbeatQueue:
    Value: !GetAtt HeartbeatQueue.QueueName
    Description: HeartbeatQueue
  ReplicaAddrBucket:
    Value: !Ref ReplicaAddrBucket
    Description: ReplicaAddrBucket name